version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/bdd_project
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app_network
    command: sh -c "sleep 5 && node src/index.js"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
